### ISSUE TITLE
Port sicmutils to Clojurescript

### ISSUE THREAD

**Issue by sritchie** [littleredcomputer/sicmutils#40]
@littleredcomputer , I'm going to use this as a staging area to record our progress, and maybe to ask questions, until we find a more efficient format.

## Tasks

- [x] port `number` and `complex`
- [x] `numsymb`
- [ ] add trig functions for `js/BigInt`, `goog.math.{Long, Integer}`. We may need to pull in another implementation here.
- [x] add ratio support via `Fraction.js` (#84)
- [ ] add BigDecimal support via `Decimal.js`

### Presentation

- [x] `sicmutils.env`
- [x] `sicmutils.infix` (#74)

### Examples

- [x] `sicmutils.examples.central-potential`
- [x] `sicmutils.examples.double-pendulum`
- [x] `sicmutils.examples.driven-pendulum`
- [x] `sicmutils.examples.pendulum`
- [x] `sicmutils.examples.rigid-rotation`
- [x] `sicmutils.examples.top`

### Data Structures and Existing Types

- [x] `sicmutils.structure` (#48)
- [x] `sicmutils.matrix` (#49)
- [x] `sicmutils.polynomial` (#55) 
- [x] `sicmutils.polynomial-gcd` (#57)
- [x] `sicmutils.polynomial-factor` (#60)
- [x] `sicmutils.rational-function` (#62)
- [x] `sicmutils.series` (#64)
- [x] `sicmutils.function`(#66)
- [x] `sicmutils.operator` (#66)

### Analysis

- [x] `sicmutils.analyze` (#55)
- [x] `sicmutils.simplify` (#63)

### Calculus

- [x] `sicmutils.calculus.basis` (#50)
- [x] `sicmutils.calculus.coordinate` (#72)
- [x] `sicmutils.calculus.covariant` (#73)
- [x] `sicmutils.calculus.derivative` (#66)
- [x] `sicmutils.calculus.form-field` (#72)
- [x] `sicmutils.calculus.manifold` (#70)
- [x] `sicmutils.calculus.map`(#73)
- [x] `sicmutils.calculus.vector-field` (#72)

### Numerical

- [x] `sicmutils.numerical.compile` (#68)
- [x] `sicmutils.numerical.integrate` (#77)
- [x] `sicmutils.numerical.minimize` (#77)
- [x] `sicmutils.numerical.ode` (#77)

### Mechanics

- [x] `sicmutils.mechanics.hamilton` (#79)
- [x] `sicmutils.mechanics.lagrange` (#78)
- [x] `sicmutils.mechanics.rigid` (#79)
- [x] `sicmutils.mechanics.rotation`(#69)

# Outstanding Issues

These questions came up during the conversion.

### Misc

- [x] in `sicmutils.numerical.compile-test`, two tests are deactivated because `eval` doesn't work out of the box in `cljs`. that requires self-hosted mode, which we'll have to configure and re-enable the tests.

### Numerics

- [ ] The `g/div` implementations in `number` catch, for example, two `goog.math.Long`s divided, since `g/div` is defined between `::v/number` instances. This is wrong; they should probably error. Do we want to explicitly catch and error? Or add a new type, `::inexact-number`... probably the former.
- [ ] in numbers.cljc, we have `(derive ::integral ::v/number)`. This is probably NOT right; we should have `(derive ::integral ::x/numerical-expression)`. This causes issues with the `number?` sprinkled all around. The former is bad because it causes us to try and divide `goog.math.Long` using `/`, which truncates.

### Structure
- [x] figure out how to extend the arity by implementing some sort of variadic form

### Polynomial

- [ ] Polynomial currently calls methods from `sicmutils.numsymb` like `sym/add`, etc directly. I think we can have the polynomial methods call the fully generic `g/add` etc if we're more careful with our types. This would let us move some of the optimizations around `numsymb` without breaking code. #47 ran into trouble because of this, for example.

### Matrix

The matrix component is itching to be more general. A project like https://github.com/originrose/aljabr would give us a cheap multidimensional array implementation in clj/cljs.

We could rebuild the matrix namespace on `core.matrix`, and implement the generics in terms of `core.matrix` operations.

**Comment by sritchie** [comment]
This is done!!!
